# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time'], 'verbose_name': '\u6587\u7ae0\u7ba1\u7406', 'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': '\u8bc4\u8bba\u7ba1\u7406', 'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b\u7ba1\u7406', 'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e\u7ba1\u7406', 'verbose_name_plural': '\u6807\u7b7e\u7ba1\u7406'},
        ),
    ]
