# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('head_img', models.ImageField(upload_to=b'uploads', verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe5\x9b\xbe\xe7\x89\x87')),
                ('summary', models.CharField(max_length=55, verbose_name=b'\xe6\xa6\x82\xe8\xa7\x88')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe6\x97\xa5\xe6\x9c\x9f')),
                ('hidden', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x9a\x90\xe8\x97\x8f')),
                ('priority', models.IntegerField(default=1000, verbose_name=b'\xe7\xbd\xae\xe9\xa1\xb6?')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u7ba1\u7406',
                'verbose_name_plural': '\u5206\u7c7b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('comment', models.TextField(max_length=1000, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.Article', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='BBS.Comment', verbose_name=b'\xe7\x88\xb6\xe8\xaf\x84\xe8\xae\xba')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ec4\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u7ec4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('groups', models.ManyToManyField(to='BBS.UserGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='thumbup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.UserProfile', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
        migrations.AddField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(to='BBS.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS.Category', verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb'),
        ),
    ]
