# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-23 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0002_auto_20161124_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba\u7ba1\u7406', 'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='thumbup',
            options={'verbose_name': '\u70b9\u8d5e\u7ba1\u7406', 'verbose_name_plural': '\u70b9\u8d5e\u7ba1\u7406'},
        ),
    ]
