# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0003_auto_20161124_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba'),
        ),
    ]
