# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_auto_20161128_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
