# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='\u4f5c\u8005\u59d3\u540d')),
                ('group', models.CharField(default='', max_length=256, verbose_name='\u6240\u5c5e\u7fa4\u7ec4')),
                ('profile', models.TextField(default='', max_length=256, verbose_name='\u4e2a\u4eba\u8d44\u6599')),
                ('password', models.CharField(default='', max_length=256, verbose_name='\u5bc6\u7801')),
                ('register_date', models.DateField(verbose_name='\u6ce8\u518c\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u4f5c\u8005\u7ba1\u7406',
                'verbose_name_plural': '\u4f5c\u8005\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5206\u7c7b\u540d')),
                ('intro', models.TextField(default='', verbose_name='\u7c7b\u4ecb\u7ecd')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u8bfe\u7a0b\u5206\u7c7b',
                'verbose_name_plural': '\u8bfe\u7a0b\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('comment_date', models.DateTimeField(verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('thumbup_num', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u7ba1\u7406',
                'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0bID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d')),
                ('img', models.ImageField(null=True, upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u8bfe\u7a0b\u5c01\u9762')),
                ('intro', models.TextField(default='', verbose_name='\u4ecb\u7ecd')),
                ('board', models.TextField(default='', verbose_name='\u516c\u544a\u677f')),
                ('arrange', models.TextField(default='', verbose_name='\u5b89\u6392')),
                ('lecture', models.FileField(default='', upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u8bb2\u4e49')),
                ('vedio', models.FileField(default='', upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u89c6\u9891')),
                ('homework', models.FileField(default='', null=True, upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u4f5c\u4e1a')),
                ('description', models.TextField(default='', verbose_name='\u8bf4\u660e')),
                ('thumbup_num', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('collect_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('pub_date', models.DateField(verbose_name='\u4e0a\u4f20\u65e5\u671f')),
                ('update_time', models.DateField(null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('dead_line', models.DateField(verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('published', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4e0a\u4f20\u4e86\uff1f')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Author', verbose_name='\u4f5c\u8005')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Category', verbose_name='\u8bfe\u7a0b\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u7ba1\u7406',
                'verbose_name_plural': '\u8bfe\u7a0b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Comment', verbose_name='\u70b9\u8d5e\u8bc4\u8bba\u8bc4\u8bba')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Course', verbose_name='\u70b9\u8d5e\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u7ba1\u7406',
                'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=256, verbose_name='\u6635\u79f0')),
                ('username', models.CharField(default='', max_length=256, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(default='', max_length=256, verbose_name='\u5bc6\u7801')),
                ('usergroup', models.CharField(default='', max_length=256, verbose_name='\u7528\u6237\u7ec4')),
                ('profile', models.TextField(default='', max_length=256, verbose_name='\u4e2a\u4eba\u8d44\u6599')),
                ('register_date', models.DateField(verbose_name='\u6ce8\u518c\u65e5\u671f')),
            ],
            options={
                'ordering': ['username'],
                'verbose_name': '\u7528\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='thumbup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.User', verbose_name='\u70b9\u8d5e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Course', verbose_name='\u8bc4\u8bba\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.User', verbose_name='\u8bc4\u8bba\u7528\u6237'),
        ),
    ]
