# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='arrange',
            field=models.TextField(default='', null=True, verbose_name='\u5b89\u6392'),
        ),
        migrations.AlterField(
            model_name='course',
            name='board',
            field=models.TextField(default='', null=True, verbose_name='\u516c\u544a\u677f'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.TextField(default='', null=True, verbose_name='\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture',
            field=models.FileField(default='', null=True, upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u8bb2\u4e49'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vedio',
            field=models.FileField(default='', null=True, upload_to='CourseApp/static/images/courseimg/courseid', verbose_name='\u89c6\u9891'),
        ),
    ]
