# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_auto_20161127_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='arrange',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='\u5b89\u6392'),
        ),
        migrations.AlterField(
            model_name='course',
            name='board',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='\u516c\u544a\u677f'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='course',
            name='homework',
            field=models.FileField(default='', null=True, upload_to='CourseApp/static/chomework/courseid', verbose_name='\u4f5c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture',
            field=models.FileField(default='', null=True, upload_to='CourseApp/static/cimg/courseid', verbose_name='\u8bb2\u4e49'),
        ),
        migrations.AlterField(
            model_name='course',
            name='vedio',
            field=models.FileField(default='', null=True, upload_to='CourseApp/static/cvedio/courseid', verbose_name='\u89c6\u9891'),
        ),
    ]
