# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u9898\u76ee')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='\u4f5c\u8005')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('thumbup_num', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('collect_num', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('comment_num', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570')),
                ('pub_date', models.DateTimeField(verbose_name='\u4e0a\u4f20\u65e5\u671f')),
                ('update_time', models.DateTimeField(null=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('published', models.BooleanField(default=True, verbose_name='\u4e0a\u4f20\u4e86\u5417?')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7ba1\u7406',
                'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='\u4f5c\u8005\u59d3\u540d')),
                ('group', models.CharField(default='', max_length=256, verbose_name='\u6240\u5c5e\u7fa4\u7ec4')),
                ('profile', models.TextField(default='', max_length=256, verbose_name='\u4e2a\u4eba\u8d44\u6599')),
                ('password', models.CharField(max_length=256, verbose_name='\u5bc6\u7801')),
                ('register_date', models.DateField(verbose_name='\u6ce8\u518c\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
                ('intro', models.TextField(default='', verbose_name='\u5206\u7c7b\u4ecb\u7ecd')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('comment_date', models.DateField(null=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('thumbup', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570')),
                ('collect', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FocusApp.Article', verbose_name='\u8bc4\u8bba\u6587\u7ae0')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FocusApp.Author', verbose_name='\u6587\u7ae0\u4f5c\u8005')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='CourseApp.User', verbose_name='\u8bc4\u8bba\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FocusApp.Article', verbose_name='\u70b9\u8d5e\u6587\u7ae0')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbup_comment', to='FocusApp.Comment', verbose_name='\u70b9\u8d5e\u8bc4\u8bba')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbup_user', to='CourseApp.User', verbose_name='\u70b9\u8d5e\u7528\u6237')),
            ],
        ),
    ]
