# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': '\u4f5c\u8005\u7ba1\u7406', 'verbose_name_plural': '\u4f5c\u8005\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '\u5206\u7c7b\u7ba1\u7406', 'verbose_name_plural': '\u5206\u7c7b\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba\u7ba1\u7406', 'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406'},
        ),
    ]
