# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0002_auto_20161121_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9'),
        ),
    ]
