# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 09:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0003_auto_20161129_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=ckeditor.fields.RichTextField(default='', max_length=256, verbose_name='\u4e2a\u4eba\u8d44\u6599'),
        ),
        migrations.AlterField(
            model_name='category',
            name='intro',
            field=ckeditor.fields.RichTextField(default='', verbose_name='\u5206\u7c7b\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
    ]
